class_name MapLoader
extends Node3D
## Builds a playable world from a map GLB and its layout JSON (both generated by Blender scripts).

var map_name := ""
var layout: Dictionary = {}
var nav_region: NavigationRegion3D
var map_scene: Node3D
var fx: Fx
var zone_chunks: Dictionary = {}     # zone name -> [VisualInstance3D]


static func layout_path(mname: String) -> String:
	return "res://assets/models/map/%s_layout.json" % mname


static func model_path(mname: String) -> String:
	return "res://assets/models/map/%s.glb" % mname


func build(mname: String) -> bool:
	map_name = mname
	name = "World"
	var f := FileAccess.open(layout_path(mname), FileAccess.READ)
	if f == null:
		push_error("MapLoader: missing layout for " + mname)
		return false
	layout = JSON.parse_string(f.get_as_text())
	var scene: PackedScene = load(model_path(mname)) if ResourceLoader.exists(model_path(mname)) else null
	if scene == null:
		push_error("MapLoader: missing model for " + mname)
		return false
	nav_region = NavigationRegion3D.new()
	nav_region.name = "Nav"
	add_child(nav_region)
	map_scene = scene.instantiate()
	map_scene.name = "MapGeometry"
	nav_region.add_child(map_scene)
	_configure_geometry()
	_build_environment()
	_build_ladders()
	_bake_navigation()
	if DisplayServer.get_name() != "headless":
		fx = Fx.new()
		fx.name = "Fx"
		add_child(fx)
	Match.set_layout(layout)
	return true


func _configure_geometry() -> void:
	for node in map_scene.find_children("*", "", true, false):
		if node is StaticBody3D:
			node.collision_layer = 1
			node.collision_mask = 0
			if node.name.begins_with("railings"):
				node.collision_layer = 4   # blocks players only; bullets pass between the bars
		if node is MeshInstance3D:
			var n: String = node.name
			if n.begins_with("floor") or n.begins_with("walls"):
				node.gi_mode = GeometryInstance3D.GI_MODE_STATIC
			if n.begins_with("wall_") and not n.begins_with("walls"):
				node.visible = false   # occluder source meshes (should already be stripped by -occonly)
			var zone := _zone_from_name(n)
			if zone != "":
				zone_chunks.get_or_add(zone, []).append(node)
			# props chunk visibility ranges for cheap LOD culling
			if n.begins_with("props") or n.begins_with("railings"):
				node.visibility_range_end = 140.0
				node.visibility_range_end_margin = 10.0


func _zone_from_name(n: String) -> String:
	var idx := n.find("_t")
	if idx < 0:
		return ""
	return n.substr(idx + 1).split("-")[0].split("_LOD")[0]


func _build_environment() -> void:
	var env := WorldEnvironment.new()
	var e := Environment.new()
	e.background_mode = Environment.BG_SKY
	var sky := Sky.new()
	var mat := ProceduralSkyMaterial.new()
	mat.sky_top_color = Color(0.22, 0.3, 0.42)
	mat.sky_horizon_color = Color(0.55, 0.47, 0.4)
	mat.ground_bottom_color = Color(0.12, 0.11, 0.1)
	mat.ground_horizon_color = Color(0.35, 0.3, 0.27)
	mat.sky_energy_multiplier = 0.55
	mat.sun_angle_max = 20.0
	sky.sky_material = mat
	e.sky = sky
	e.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	e.ambient_light_color = Color(0.4, 0.42, 0.47)
	e.ambient_light_energy = 0.45
	e.reflected_light_source = Environment.REFLECTION_SOURCE_DISABLED
	e.tonemap_mode = Environment.TONE_MAPPER_FILMIC
	e.tonemap_exposure = 0.75
	e.tonemap_white = 1.0
	e.fog_enabled = true
	e.fog_light_color = Color(0.35, 0.33, 0.3)
	e.fog_density = 0.0025
	e.glow_enabled = false
	e.ssao_enabled = DisplayServer.get_name() != "headless" and RenderingServer.get_current_rendering_method() == "forward_plus"
	env.environment = e
	add_child(env)
	var sun := DirectionalLight3D.new()
	sun.name = "Sun"
	sun.light_color = Color(1.0, 0.92, 0.8)
	sun.light_energy = 0.6
	sun.shadow_enabled = true
	sun.directional_shadow_mode = DirectionalLight3D.SHADOW_PARALLEL_4_SPLITS
	sun.directional_shadow_max_distance = 120.0
	sun.rotation_degrees = Vector3(-52, 35, 0)
	add_child(sun)
	var count := 0
	for l in layout.get("lights", []):
		if count > 40:
			break
		var o := OmniLight3D.new()
		o.light_color = Color(1.0, 0.9, 0.75)
		o.light_energy = 0.9
		o.omni_range = 12.0
		o.shadow_enabled = false
		o.position = Vector3(l.pos[0], l.pos[1], l.pos[2])
		add_child(o)
		count += 1


func _build_ladders() -> void:
	for l in layout.get("ladders", []):
		var ladder := Ladder.new()
		add_child(ladder)
		ladder.setup(Vector3(l.pos[0], l.pos[1], l.pos[2]), Vector3(l.top[0], l.top[1], l.top[2]), float(l.height), Vector3(l.climb_dir[0], l.climb_dir[1], l.climb_dir[2]))


func _bake_navigation() -> void:
	var nm := NavigationMesh.new()
	nm.geometry_parsed_geometry_type = NavigationMesh.PARSED_GEOMETRY_STATIC_COLLIDERS
	nm.geometry_collision_mask = 1
	nm.cell_size = 0.25
	nm.cell_height = 0.25
	nm.agent_radius = 0.42
	nm.agent_height = 1.8
	nm.agent_max_climb = 0.45
	nm.agent_max_slope = 48.0
	nm.region_min_size = 4.0
	nm.edge_max_length = 12.0
	nm.detail_sample_distance = 4.0
	nav_region.navigation_mesh = nm
	nav_region.bake_navigation_mesh(false)
	print("[map] navmesh baked: %d polygons" % nm.get_polygon_count())


func spawn_points(team: int) -> Array:
	return layout.get("spawns", {}).get("attackers" if team == Teams.ATTACKERS else "defenders", [])


func validate_spawns() -> PackedStringArray:
	## Spawn validation: every spawn must be on the navmesh and not inside geometry.
	var problems := PackedStringArray()
	var map_rid := get_world_3d().navigation_map
	for key in ["attackers", "defenders"]:
		var pts: Array = layout.get("spawns", {}).get(key, [])
		if pts.size() < Match.rules.team_size:
			problems.append("%s has only %d spawns" % [key, pts.size()])
		for s in pts:
			var p := Vector3(s.pos[0], s.pos[1], s.pos[2])
			var closest := NavigationServer3D.map_get_closest_point(map_rid, p)
			if closest.distance_to(p) > 1.0:
				problems.append("%s spawn at %s is %.1fm off the navmesh" % [key, p, closest.distance_to(p)])
			var space := get_world_3d().direct_space_state
			var q := PhysicsPointQueryParameters3D.new()
			q.position = p + Vector3(0, 1.0, 0)
			q.collision_mask = 1
			if not space.intersect_point(q, 1).is_empty():
				problems.append("%s spawn at %s is inside geometry" % [key, p])
	return problems
